version: '2'
services:
    2bp-app:
        image: 2bp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://2bp-postgresql:5432/2bP
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    2bp-postgresql:
        extends:
            file: postgresql.yml
            service: 2bp-postgresql
